type: huggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-large-patch14
  - name: sun397
    path: tanganke/clip-vit-large-patch14_sun397
  - name: stanford_cars
    path: tanganke/clip-vit-large-patch14_stanford-cars
  - name: resisc45
    path: tanganke/clip-vit-large-patch14_resisc45
  - name: eurosat
    path: tanganke/clip-vit-large-patch14_eurosat
  - name: svhn
    path: tanganke/clip-vit-large-patch14_svhn
  - name: gtsrb
    path: tanganke/clip-vit-large-patch14_gtsrb
  - name: mnist
    path: tanganke/clip-vit-large-patch14_mnist
  - name: dtd
    path: tanganke/clip-vit-large-patch14_dtd

# The following datasets are used for test-time adaptation
dataset_type: huggingface_image_classification
tta_datasets:
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object: 
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: test
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: test
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: test
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: test
  - name: mnist
    dataset:
      name: mnist
      split: test
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: test
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test
