defaults:
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
  - _self_
_target_: fusion_bench.taskpool.image_classification.ImageClassificationTaskPool
_recursive_: False
processor: facebook/convnext-base-224
dataloader_kwargs:
  batch_size: 32
  num_workers: 0
