# The 20 task used in the paper: 
# Wang et al. Localizing Task Information for Improved Model Merging and Compression
# http://arxiv.org/abs/2405.07813
defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models: clip-vit-base-patch32_TALL16
  - /dataset/image_classification/train@train_datasets: TALL16
  - /dataset/image_classification/test@test_datasets: TALL16
