_target_: fusion_bench.method.RegMeanAlgorithmForCLIP
# list, regular expression of names of parameters that need to be excluded
exclude_param_names_regex: []
# numbers of examples to compute regmean weights
num_regmean_examples: 256
weight_transpose: true
# float, reduce non-diagonal elements in regmean weights by multiplying this scalar
reduce_non_diagonal_ratio: 0.95
dataloader_kwargs:
  batch_size: 32
  num_workers: 0
