defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
  - /dataset/image_classification/test@val_datasets:
      - sun397
  - _self_
_target_: fusion_bench.modelpool.ResNetForImageClassificationPool
_recursive_: False
type: transformers
models:
  _pretrained_:
    config_path: microsoft/resnet-18
    pretrained: true
    dataset_name: sun397