_target_: fusion_bench.method.svd_projection.weight_average.WeightAverageForCLIP

# shuffle the order of the models
shuffle_order: true
# the random seed to use
seed: null
# save the merged model on every step
save_on_every_step: true
# evaluate the merged model on every step
evaluate_on_every_step: true
